# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70b485e0371db4d92385dd82c388d483d813c0492d599bccf8e94dddbfc978b03eb0f81226f41bb418a6f03bb862c8b97dfcb435570a88b945ea6a5833b71368

test:
  secret_key_base: 3c911e86adb444fce025c24fead4b073ba86f17ac55f22ef48c9f1052c7e693f6f39828d69a541f401cb8c69fc30f36c17ca69efc137e7865b1b00d7fbc69d77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
